name: Isntall awscli and awsebcli on Mac

on: push

jobs:
  install:
    name: Install commands
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master

      - name: Install awscli and awsebcli
        run: |
          brew install awscli awsebcli
          brew upgrade

      - name: Check
        run: |
          aws --version
          eb --version