name: Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test tag
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Get latest tag
        run: git tag -l | grep -E "^ecs.[0-9]{8}\.[0-9]+" | sort -r | head -n 1
