name: Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test tag
    steps:
      - uses: actions/checkout@v2

      - name: Get latest tag
        run: git tag -l | head -n 3
