name: Workflow Run Trigger

on:
  workflow_run:
    workflows:
      - Tag
    types:
      - completed

jobs:
  echo:
    name: Echo
    runs-on: ubuntu-latest
    steps:
      - run: cat ${{ github.event_path.workflow_run }} | jq '.workflow_run.conclusion'
